name: fortranbox
channels:
  - conda-forge
dependencies:
  - gfortran
  - make          # UNIX environments; ignored on native Windows
  - cmake
  - git
  - python=3.11   # Optional: useful if you use Python scripts/tools
  - pip
  - fpm       # Optional: fpm via pip (can be installed manually)
  - ford
