name = "test_1178"
version = "0.1.0"
license = "license"
author = "albert"
maintainer = "92109627+Albkat@users.noreply.github.com"
copyright = "Copyright 2025, albert"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
openmp = "*"

